server:
  port: "8080"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "auth_service"
  sslmode: "disable"

jwt:
  secret: "your-secret-key"
  expiration: 24h # 24 hours
