server:
  isProductionMode: false
database:
  host: localhost
  port: 5432
  dbname: auth_service
  username: postgres
  password: postgres
  sslmode: disable
  timezone: Asia/Bangkok
  schema: public
  gormlogenable: true
